using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace ConvertirJson.Mapeos
{
    public class OrdenECF
    {
        public string Orden { get; set; }
        public string CasoPrueba { get; set; }
        public string Version { get; set; }
        public string TipoeCF { get; set; }
        public string ENCF { get; set; }
        public string FechaVencimientoSecuencia { get; set; }
        public string IndicadorNotaCredito { get; set; }
        public string IndicadorEnvioDiferido { get; set; }
        public string IndicadorMontoGravado { get; set; }
        public string TipoIngresos { get; set; }
        public string TipoPago { get; set; }
        public string FechaLimitePago { get; set; }
        public string TerminoPago { get; set; }
        public string FormaPago1 { get; set; }
        public string MontoPago1 { get; set; }
        public string FormaPago2 { get; set; }
        public string MontoPago2 { get; set; }
        public string FormaPago3 { get; set; }
        public string MontoPago3 { get; set; }
        public string FormaPago4 { get; set; }
        public string MontoPago4 { get; set; }
        public string FormaPago5 { get; set; }
        public string MontoPago5 { get; set; }
        public string FormaPago6 { get; set; }
        public string MontoPago6 { get; set; }
        public string FormaPago7 { get; set; }
        public string MontoPago7 { get; set; }
        public string TipoCuentaPago { get; set; }
        public string NumeroCuentaPago { get; set; }
        public string BancoPago { get; set; }
        public string FechaDesde { get; set; }
        public string FechaHasta { get; set; }
        public string TotalPaginas { get; set; }
        public string RNCEmisor { get; set; }
        public string RazonSocialEmisor { get; set; }
        public string NombreComercial { get; set; }
        public string Sucursal { get; set; }
        public string DireccionEmisor { get; set; }
        public string Municipio { get; set; }
        public string Provincia { get; set; }
        public string TelefonoEmisor1 { get; set; }
        public string TelefonoEmisor2 { get; set; }
        public string TelefonoEmisor3 { get; set; }
        public string CorreoEmisor { get; set; }
        public string WebSite { get; set; }
        public string ActividadEconomica { get; set; }
        public string CodigoVendedor { get; set; }
        public string NumeroFacturaInterna { get; set; }
        public string NumeroPedidoInterno { get; set; }
        public string ZonaVenta { get; set; }
        public string RutaVenta { get; set; }
        public string InformacionAdicionalEmisor { get; set; }
        public string FechaEmision { get; set; }
        public string RNCComprador { get; set; }
        public string IdentificadorExtranjero { get; set; }
        public string RazonSocialComprador { get; set; }
        public string ContactoComprador { get; set; }
        public string CorreoComprador { get; set; }
        public string DireccionComprador { get; set; }
        public string MunicipioComprador { get; set; }
        public string ProvinciaComprador { get; set; }
        public string PaisComprador { get; set; }
        public string FechaEntrega { get; set; }
        public string ContactoEntrega { get; set; }
        public string DireccionEntrega { get; set; }
        public string TelefonoAdicional { get; set; }
        public string FechaOrdenCompra { get; set; }
        public string NumeroOrdenCompra { get; set; }
        public string CodigoInternoComprador { get; set; }
        public string ResponsablePago { get; set; }
        public string InformacionAdicionalComprador { get; set; }
        public string FechaEmbarque { get; set; }
        public string NumeroEmbarque { get; set; }
        public string NumeroContenedor { get; set; }
        public string NumeroReferencia { get; set; }
        public string NombrePuertoEmbarque { get; set; }
        public string CondicionesEntrega { get; set; }
        public string TotalFob { get; set; }
        public string Seguro { get; set; }
        public string Flete { get; set; }
        public string OtrosGastos { get; set; }
        public string TotalCif { get; set; }
        public string RegimenAduanero { get; set; }
        public string NombrePuertoSalida { get; set; }
        public string NombrePuertoDesembarque { get; set; }
        public string PesoBruto { get; set; }
        public string PesoNeto { get; set; }
        public string UnidadPesoBruto { get; set; }
        public string UnidadPesoNeto { get; set; }
        public string CantidadBulto { get; set; }
        public string UnidadBulto { get; set; }
        public string VolumenBulto { get; set; }
        public string UnidadVolumen { get; set; }
        public string ViaTransporte { get; set; }
        public string PaisOrigen { get; set; }
        public string DireccionDestino { get; set; }
        public string PaisDestino { get; set; }
        public string RNCIdentificacionCompaniaTransportista { get; set; }
        public string NombreCompaniaTransportista { get; set; }
        public string NumeroViaje { get; set; }
        public string Conductor { get; set; }
        public string DocumentoTransporte { get; set; }
        public string Ficha { get; set; }
        public string Placa { get; set; }
        public string RutaTransporte { get; set; }
        public string ZonaTransporte { get; set; }
        public string NumeroAlbaran { get; set; }
        public string MontoGravadoTotal { get; set; }
        public string MontoGravadoI1 { get; set; }
        public string MontoGravadoI2 { get; set; }
        public string MontoGravadoI3 { get; set; }
        public string MontoExento { get; set; }
        public string ITBIS1 { get; set; }
        public string ITBIS2 { get; set; }
        public string ITBIS3 { get; set; }
        public string TotalITBIS { get; set; }
        public string TotalITBIS1 { get; set; }
        public string TotalITBIS2 { get; set; }
        public string TotalITBIS3 { get; set; }
        public string MontoImpuestoAdicional { get; set; }
        public string TipoImpuesto1 { get; set; }
        public string TasaImpuestoAdicional1 { get; set; }
        public string MontoImpuestoSelectivoConsumoEspecifico1 { get; set; }
        public string MontoImpuestoSelectivoConsumoAdvalorem1 { get; set; }
        public string OtrosImpuestosAdicionales1 { get; set; }
        public string MontoTotal { get; set; }
        public string MontoNoFacturable { get; set; }
        public string MontoPeriodo { get; set; }
        public string SaldoAnterior { get; set; }
        public string MontoAvancePago { get; set; }
        public string ValorPagar { get; set; }
        public string TotalITBISRetenido { get; set; }
        public string TotalISRRetencion { get; set; }
        public string TotalITBISPercepcion { get; set; }
        public string TotalISRPercepcion { get; set; }
        public string TipoMoneda { get; set; }
        public string TipoCambio { get; set; }
        public string MontoGravadoTotalOtraMoneda { get; set; }
        public string MontoGravado1OtraMoneda { get; set; }
        public string MontoGravado2OtraMoneda { get; set; }
        public string MontoGravado3OtraMoneda { get; set; }
        public string MontoExentoOtraMoneda { get; set; }
        public string TotalITBISOtraMoneda { get; set; }
        public string TotalITBIS1OtraMoneda { get; set; }
        public string TotalITBIS2OtraMoneda { get; set; }
        public string TotalITBIS3OtraMoneda { get; set; }
        public string MontoImpuestoAdicionalOtraMoneda { get; set; }
        public string MontoTotalOtraMoneda { get; set; }
        public List<Items> Detalles { get; set; } = new List<Items>();
    }
}
